title: Your awesome title
email: k.chausheva@gmail.com
phone-number: 359 883 222 003
destination: docs
description: Front End Developer, IoT Enthusiast, AI hobbyist
baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://localhost:4000' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
